import type { StepDef } from './types';

/**
 * 验收用引导流程：
 *  欢迎 → 账户类型 → 资料表单 → 隐私授权 → [企业验证 → 团队邀请] / [通知偏好] → 服务条款 → 完成
 * 企业线与个人线通过节点 visible 条件分流；每个步骤有多个版本，命中规则 = 第一个 when 为真，否则基线版本。
 */
export const STEPS: StepDef[] = [
  {
    id: 'welcome',
    required: false,
    pos: { x: 40, y: 150 },
    versions: [
      {
        version: 'v1',
        owner: 'product',
        publishedAt: '2026-07-01',
        changelog: '初版欢迎页',
        kind: 'info',
        title: '欢迎使用 Workspace',
        body: '三步完成开通，全程约一分钟。',
        skippable: false,
        primaryLabel: '开始',
      },
      {
        version: 'v2',
        owner: 'design',
        publishedAt: '2026-09-02',
        changelog: '移动端紧凑版，字号与间距重做',
        when: { field: 'device', key: '', op: '==', value: 'mobile' },
        kind: 'info',
        title: '欢迎',
        body: '一分钟开通。',
        skippable: false,
        primaryLabel: '开始',
      },
    ],
    edges: [{ id: 'e_welcome_account', to: 'account_type' }],
  },
  {
    id: 'account_type',
    required: true,
    pos: { x: 250, y: 150 },
    versions: [
      {
        version: 'v1',
        owner: 'product',
        publishedAt: '2026-07-10',
        changelog: '个人 / 团队 二选一',
        kind: 'choice',
        title: '你要开通什么账户？',
        body: '后续资料与验证步骤会据此变化。',
        skippable: false,
        primaryLabel: '下一步',
        choices: [
          { id: 'personal', label: '个人使用', sets: { plan: 'personal' } },
          { id: 'team', label: '小团队', sets: { plan: 'team' } },
        ],
      },
      {
        version: 'v2',
        owner: 'legal',
        publishedAt: '2026-08-20',
        changelog: '欧盟版：文案须说明账户类型关联的数据控制者',
        when: { field: 'region', key: '', op: '==', value: 'EU' },
        kind: 'choice',
        title: '选择账户类型',
        body: '根据 GDPR 第 26 条，团队账户将设置联合数据控制者关系。',
        skippable: false,
        primaryLabel: '同意并继续',
        choices: [
          { id: 'personal', label: '个人使用', sets: { plan: 'personal' } },
          { id: 'enterprise', label: '企业/组织', sets: { plan: 'enterprise' } },
        ],
      },
      {
        version: 'v3',
        owner: 'product',
        publishedAt: '2026-09-10',
        changelog: '新增企业账户入口',
        kind: 'choice',
        title: '你要开通什么账户？',
        body: '企业账户需要域名验证，个人版立即可用。',
        skippable: false,
        primaryLabel: '下一步',
        choices: [
          { id: 'personal', label: '个人使用', sets: { plan: 'personal' } },
          { id: 'enterprise', label: '企业/组织', sets: { plan: 'enterprise' } },
        ],
      },
    ],
    edges: [{ id: 'e_account_profile', to: 'profile_form' }],
  },
  {
    id: 'profile_form',
    required: true,
    pos: { x: 470, y: 150 },
    versions: [
      {
        version: 'v1',
        owner: 'product',
        publishedAt: '2026-07-12',
        changelog: '姓名 + 公司名',
        kind: 'form',
        title: '完善资料',
        body: '公司名在企业流程中用于验证。',
        skippable: false,
        primaryLabel: '保存并继续',
        fields: [
          { key: 'name', label: '姓名', type: 'text', required: true, placeholder: '张小明' },
          { key: 'company', label: '公司', type: 'text', required: false, placeholder: '选填' },
        ],
        setsOnConfirm: { profileDone: true },
      },
      {
        version: 'v2',
        owner: 'design',
        publishedAt: '2026-09-05',
        changelog: '移动端单列紧凑表单，公司字段折叠',
        when: { field: 'device', key: '', op: '==', value: 'mobile' },
        kind: 'form',
        title: '资料',
        body: '',
        skippable: false,
        primaryLabel: '继续',
        fields: [
          { key: 'name', label: '姓名', type: 'text', required: true, placeholder: '必填' },
          {
            key: 'company',
            label: '公司（企业必填）',
            type: 'text',
            required: false,
            placeholder: '选填',
          },
        ],
        setsOnConfirm: { profileDone: true },
      },
      {
        version: 'v3',
        owner: 'legal',
        publishedAt: '2026-09-12',
        changelog: '企业账户的公司字段升级为必填，用于合同主体',
        when: { all: [{ field: 'ctx', key: 'plan', op: '==', value: 'enterprise' }] },
        kind: 'form',
        title: '完善资料（企业）',
        body: '请填写与营业执照一致的公司全称。',
        skippable: false,
        primaryLabel: '保存并继续',
        fields: [
          { key: 'name', label: '姓名', type: 'text', required: true },
          { key: 'company', label: '公司全称', type: 'text', required: true },
          { key: 'agreeProfile', label: '资料将用于合同与验证', type: 'checkbox', required: true },
        ],
        setsOnConfirm: { profileDone: true },
      },
    ],
    edges: [{ id: 'e_profile_privacy', to: 'privacy_consent' }],
  },
  {
    id: 'privacy_consent',
    required: true,
    pos: { x: 690, y: 150 },
    versions: [
      {
        version: 'v1',
        owner: 'product',
        publishedAt: '2026-07-15',
        changelog: '首版隐私授权，允许稍后在设置中修改（可跳过）',
        kind: 'consent',
        title: '隐私数据授权',
        body: '我们将同步你的通讯录用于团队推荐。',
        skippable: true,
        primaryLabel: '同意授权',
        skipLabel: '以后再说',
        setsOnConfirm: { privacy: 'granted' },
        setsOnSkip: { privacy: 'deferred' },
      },
      {
        version: 'v2',
        owner: 'legal',
        publishedAt: '2026-08-25',
        changelog: '欧盟版：GDPR 明确同意，不可跳过，必须勾选',
        when: { field: 'region', key: '', op: '==', value: 'EU' },
        kind: 'consent',
        title: '隐私数据授权（GDPR）',
        body: '依据 GDPR 第 6(1)(a) 条，我们需要你的明确同意才能同步通讯录。你可以随时撤回。',
        skippable: false,
        primaryLabel: '我同意',
        fields: [{ key: 'privacyCheck', label: '我已阅读并同意《隐私声明》', type: 'checkbox', required: true }],
        setsOnConfirm: { privacy: 'granted', privacyVersion: 'gdpr-v2' },
      },
      {
        version: 'v3',
        owner: 'legal',
        publishedAt: '2026-09-08',
        changelog: '美区版：补充 CCPA 选择权说明，仍需明确选择，不可跳过',
        when: { field: 'region', key: '', op: '==', value: 'US' },
        kind: 'consent',
        title: '隐私选择',
        body: '根据 CPA，你有权选择不出售个人信息。继续即表示你已阅读我们的隐私政策。',
        skippable: false,
        primaryLabel: '确认',
        setsOnConfirm: { privacy: 'granted', privacyVersion: 'ccpa-v3' },
      },
    ],
    edges: [
      { id: 'e_priv_ent', to: 'enterprise_verify', when: { field: 'ctx', key: 'plan', op: '==', value: 'enterprise' }, label: 'plan=enterprise' },
      { id: 'e_priv_notif', to: 'notification_pref', label: '默认（非企业）' },
    ],
  },
  {
    id: 'enterprise_verify',
    required: false,
    visible: { field: 'ctx', key: 'plan', op: '==', value: 'enterprise' },
    pos: { x: 900, y: 30 },
    versions: [
      {
        version: 'v1',
        owner: 'product',
        publishedAt: '2026-07-20',
        changelog: '企业邮箱域名验证',
        kind: 'info',
        title: '域名验证',
        body: '我们已向你的企业邮箱发送验证码（模拟：直接确认即通过）。',
        skippable: false,
        primaryLabel: '我已完成验证',
        setsOnConfirm: { verified: true },
      },
    ],
    edges: [{ id: 'e_ent_invite', to: 'invite_team' }],
  },
  {
    id: 'invite_team',
    required: false,
    visible: { field: 'ctx', key: 'plan', op: '==', value: 'enterprise' },
    pos: { x: 1110, y: 30 },
    versions: [
      {
        version: 'v1',
        owner: 'design',
        publishedAt: '2026-08-01',
        changelog: '批量邀请成员页',
        kind: 'choice',
        title: '邀请同事',
        body: '也可以稍后在管理后台邀请。',
        skippable: true,
        primaryLabel: '邀请并继续',
        skipLabel: '稍后邀请',
        choices: [
          { id: 'inviteNow', label: '现在邀请', sets: { invite: 'now' } },
          { id: 'inviteLater', label: '稍后', sets: { invite: 'later' } },
        ],
        setsOnSkip: { invite: 'skipped' },
      },
      {
        version: 'v2',
        owner: 'product',
        publishedAt: '2026-09-15',
        changelog: '平板以上设备支持批量 CSV 入口（仅文案差异演示版本边界）',
        when: { any: [
          { field: 'device', key: '', op: '==', value: 'tablet' },
          { field: 'device', key: '', op: '==', value: 'desktop' },
        ] },
        kind: 'choice',
        title: '邀请同事',
        body: '支持批量导入 CSV，或逐人添加。',
        skippable: true,
        primaryLabel: '邀请并继续',
        skipLabel: '稍后邀请',
        choices: [
          { id: 'inviteNow', label: '批量/逐人邀请', sets: { invite: 'now' } },
          { id: 'inviteLater', label: '稍后', sets: { invite: 'later' } },
        ],
        setsOnSkip: { invite: 'skipped' },
      },
    ],
    edges: [{ id: 'e_invite_notif', to: 'notification_pref' }],
  },
  {
    id: 'notification_pref',
    required: false,
    visible: { field: 'ctx', key: 'plan', op: '!=', value: 'enterprise' },
    pos: { x: 900, y: 250 },
    versions: [
      {
        version: 'v1',
        owner: 'product',
        publishedAt: '2026-07-22',
        changelog: '个人线通知偏好',
        kind: 'choice',
        title: '通知偏好',
        body: '企业版由管理员统一配置，因此仅个人/团队账户展示此步。',
        skippable: true,
        primaryLabel: '保存',
        skipLabel: '跳过',
        choices: [
          { id: 'all', label: '接收全部通知', sets: { notify: 'all' } },
          { id: 'essential', label: '仅重要通知', sets: { notify: 'essential' } },
          { id: 'none', label: '关闭通知', sets: { notify: 'none' } },
        ],
        setsOnSkip: { notify: 'skipped' },
      },
    ],
    edges: [{ id: 'e_notif_legal', to: 'legal_terms' }],
  },
  {
    id: 'legal_terms',
    required: true,
    pos: { x: 1140, y: 150 },
    versions: [
      {
        version: 'v1',
        owner: 'legal',
        publishedAt: '2026-06-01',
        changelog: '基线服务条款（CN）',
        when: { field: 'region', key: '', op: '==', value: 'CN' },
        kind: 'consent',
        title: '服务条款',
        body: '请阅读并同意《服务协议》与《隐私政策》。',
        skippable: false,
        primaryLabel: '同意并继续',
        fields: [{ key: 'termsCheck', label: '我已阅读并同意上述条款', type: 'checkbox', required: true }],
        setsOnConfirm: { terms: 'accepted', termsVersion: 'cn-v1' },
      },
      {
        version: 'v2',
        owner: 'legal',
        publishedAt: '2026-08-30',
        changelog: '欧盟版：附 DPA 与标准合同条款',
        when: { field: 'region', key: '', op: '==', value: 'EU' },
        kind: 'consent',
        title: '服务条款与 DPA',
        body: '本服务包含数据处理协议（DPA）与欧盟标准合同条款（SCC 2021/914）。',
        skippable: false,
        primaryLabel: '同意条款与 DPA',
        fields: [
          { key: 'termsCheck', label: '同意《服务条款》', type: 'checkbox', required: true },
          { key: 'dpaCheck', label: '同意《数据处理协议》', type: 'checkbox', required: true },
        ],
        setsOnConfirm: { terms: 'accepted', termsVersion: 'eu-dpa-v2' },
      },
      {
        version: 'v3',
        owner: 'design',
        publishedAt: '2026-09-06',
        changelog: '移动端阅读优化：条款分段折叠（法务文本同 v4）',
        when: { all: [
          { field: 'device', key: '', op: '==', value: 'mobile' },
          { field: 'region', key: '', op: '!=', value: 'EU' },
        ] },
        kind: 'consent',
        title: '服务条款',
        body: '（分段折叠版）请阅读并同意《服务协议》与《隐私政策》。',
        skippable: false,
        primaryLabel: '同意',
        fields: [{ key: 'termsCheck', label: '我已阅读并同意', type: 'checkbox', required: true }],
        setsOnConfirm: { terms: 'accepted', termsVersion: 'mobile-v3' },
      },
      {
        version: 'v4',
        owner: 'legal',
        publishedAt: '2026-09-14',
        changelog: '通用新版条款（US 及其余地区兜底）',
        kind: 'consent',
        title: '服务条款',
        body: '请阅读并同意更新后的《服务协议》。',
        skippable: false,
        primaryLabel: '同意并继续',
        fields: [{ key: 'termsCheck', label: '我已阅读并同意上述条款', type: 'checkbox', required: true }],
        setsOnConfirm: { terms: 'accepted', termsVersion: 'us-v4' },
      },
    ],
    edges: [{ id: 'e_legal_done', to: 'done' }],
  },
  {
    id: 'done',
    required: false,
    pos: { x: 1360, y: 150 },
    versions: [
      {
        version: 'v1',
        owner: 'product',
        publishedAt: '2026-07-01',
        changelog: '完成页',
        kind: 'complete',
        title: '开通完成 🎉',
        body: '你可以开始使用了。',
        skippable: false,
        primaryLabel: '完成',
        setsOnConfirm: { completed: true },
      },
    ],
    edges: [],
  },
];

export const STEP_MAP: Record<string, StepDef> = Object.fromEntries(STEPS.map((s) => [s.id, s]));
export const ENTRY_STEP = 'welcome';
